 import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavbarContainer from "./components/navbar"
import Link from "next/link";
import './global.css';


//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body>
       <NavbarContainer/>
      {/*<div className="NavbarContainer">
        <Link href={'./'}>Home</Link>
        <Link href={'./about'}>About </Link>
        <ul>
          <li>Contact</li>
          <li>Blog</li>
        </ul>
  </div>
        <div className="navbar">
          <Link href={'./'}>Bosh sahifa</Link>
          <Link href={'./About'}>About Page</Link>
          <Link href={'./catalog'}>Catalog Page</Link>
  </div> */}
        {children}
        <div className="Footer-container">
          <Link href={'./'}> Footer</Link>
        </div>
        </body>
    </html>
  );
}
